### ISSUE TITLE
Bugs with MacOS

### ISSUE THREAD

**Issue by boshi-an** [google-research/robopianist#15]
Running the ipynb, I get different results as what I get on colab.

MacOS:

![Screenshot 2023-12-24 at 15 59 30](https://github.com/google-research/robopianist/assets/41010290/7d4cf6ae-4c4a-47a1-b5c8-fc36f20be385)

CoLab:

<img width="618" alt="Screenshot 2023-12-24 at 15 59 52" src="https://github.com/google-research/robopianist/assets/41010290/57d4488e-ec55-4113-930e-20b217ad220b">

**Comment by kevinzakka** [comment]
The macOS screenshot looks like you're using the updated Menagerie model but the submodule should be checking out commit 1afc8be64233dcfe943b2fe0c505ec1e87a0a13e. Can you use that commit while I debug why it's not respecting it?

**Comment by kevinzakka** [comment]
If you don't care about using the updated Shadow Hand model with newest forearm meshes, then make sure you checkout [commit 1afc8be64233dcfe943b2fe0c505ec1e87a0a13e](https://github.com/google-deepmind/mujoco_menagerie/commit/1afc8be64233dcfe943b2fe0c505ec1e87a0a13e) in the menagerie submodule.

Otherwise, update `_LEFT_HAND_QUATERNION` and `_RIGHT_HAND_QUATERNION` to `(0, -1, 0, 1)` [here](https://github.com/google-research/robopianist/blob/main/robopianist/suite/tasks/base.py#L35).

**Comment by kevinzakka** [comment]
Actually I'm wrong. Don't update left and right quaternion. Just use the specific commit please. I'll push a fix that insures the install script checks it out too. Thanks for raising this issue btw!
